Repository ultralytics/template, pull requests merged in 2024-10, with the labels that each got.

#35 Ultralytics Code Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
  README.md
  docs/README.md
  template/README.md
  tests/README.md
Labels: enhancement

#36 Update pyproject.toml
  .github/workflows/ci.yml
  pyproject.toml
  template/module1.py
  tests/test_module1.py
Labels: dependencies, enhancement

#38 Update README.md
  README.md
Labels: documentation, devops

#37 Add CI badge to README
  README.md
  template/module1.py
Labels: documentation
