Repository ultralytics/template, pull requests merged in 2025-01, with the labels that each got.

#42 Update format.yml
  .github/workflows/format.yml
Labels: enhancement, devops

#44 astral-sh/setup-uv@v5
  .github/workflows/ci.yml
Labels: dependencies, devops

#45 Set `fail-fast: false`
  .github/workflows/ci.yml
Labels: enhancement, devops

#50 Standardize license headers in TOML/YAML files
  .github/workflows/ci.yml
  .github/workflows/format.yml
  pyproject.toml
Labels: documentation, devops

#52 Update .gitignore to add PyCharm .idea
  .gitignore
Labels: devops

#53 Add unittest example
  .github/workflows/ci.yml
Labels: enhancement, devops

#55 Disable uv cache
  .github/workflows/ci.yml
Labels: dependencies, devops
